name: Terraform CD

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  terraform:
    name: Terraform Deploy
    runs-on: ubuntu-latest

    steps:
      # 1. Check out your repository code
      - name: Check out code
        uses: actions/checkout@v4

      # 2. Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          # Pin a Terraform version if you like (optional)
          terraform_version: '1.4.0'
          # This ensures Terraform CLI can authenticate with Terraform Cloud
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

  

      # 3. Terraform Init
      - name: Terraform Init
        working-directory: ./prod-terraform
        run: terraform init

      # 4. Terraform Format Check (fails CI if formatting is off)
      - name: Terraform Format
        working-directory: ./prod-terraform
        run: terraform fmt -check

      # 5. Terraform Validate (checks syntax and basic config)
      - name: Terraform Validate
        working-directory: ./prod-terraform
        run: terraform validate

      # 6. Terraform Plan (shows changes)
      - name: Terraform Plan
        working-directory: ./prod-terraform
        run: terraform plan -no-color

      # 7. Terraform Apply (only applies on push to main, not on PR)
      - name: Terraform Apply
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        working-directory: ./prod-terraform
        run: terraform apply -auto-approve -no-color
